/**
 * Pure helpers for regenerating YSHELPER_CHARACTER_ID_BY_NAME from Amber EN
 * avatar list data. Network I/O lives in the script layer.
 */

export const AMBER_EN_AVATAR_ORIGIN = "https://gi.yatta.moe";
export const AMBER_EN_AVATAR_PATH = "/api/v2/en/avatar";
export const CHARACTER_ID_MAP_MIN_COUNT = 80;
export const CHARACTER_ID_MAP_MAX_DROP_RATIO = 0.8;
export const CHARACTER_ID_PATTERN = /^\d{4,16}$/;

export type CharacterIdMap = Readonly<Record<string, string>>;

export class CharacterIdMapGenerateError extends Error {
  constructor(readonly code: string) {
    super(code);
    this.name = "CharacterIdMapGenerateError";
  }
}

export type BuildCharacterIdMapOptions = {
  /** Override for tests; production uses CHARACTER_ID_MAP_MIN_COUNT. */
  minCount?: number;
  /** Override for tests; production uses CHARACTER_ID_MAP_MAX_DROP_RATIO. */
  maxDropRatio?: number;
};

export function buildCharacterIdMapFromAmberData(
  payload: unknown,
  previous: CharacterIdMap | null = null,
  options: BuildCharacterIdMapOptions = {},
): { map: Record<string, string>; count: number } {
  const minCount = options.minCount ?? CHARACTER_ID_MAP_MIN_COUNT;
  const maxDropRatio =
    options.maxDropRatio ?? CHARACTER_ID_MAP_MAX_DROP_RATIO;
  const data = extractAmberAvatarData(payload);
  const byName = new Map<string, string>();
  const idToName = new Map<string, string>();
  let skippedInvalidIds = 0;

  for (const [rawId, entry] of Object.entries(data)) {
    if (!isRecord(entry)) {
      throw new CharacterIdMapGenerateError("invalid_avatar_entry");
    }
    // Amber list keys are the public numeric ids. Prefer the key when valid so
    // non-numeric auxiliary `id` fields cannot poison the map.
    const idFromKey = CHARACTER_ID_PATTERN.test(rawId) ? rawId : null;
    const idFromField =
      typeof entry.id === "string" || typeof entry.id === "number"
        ? String(entry.id)
        : null;
    const id =
      idFromKey ??
      (idFromField && CHARACTER_ID_PATTERN.test(idFromField)
        ? idFromField
        : null);
    if (!id) {
      // Ignore rare non-avatar keys under items; absolute min-count still applies.
      skippedInvalidIds += 1;
      continue;
    }
    if (
      idFromKey &&
      idFromField &&
      CHARACTER_ID_PATTERN.test(idFromField) &&
      idFromKey !== idFromField
    ) {
      throw new CharacterIdMapGenerateError("character_id_mismatch");
    }
    if (isTravelerId(id)) {
      continue;
    }
    const name = typeof entry.name === "string" ? entry.name.trim() : "";
    if (!name) {
      throw new CharacterIdMapGenerateError("empty_character_name");
    }
    const key = name.toLowerCase();
    if (key === "traveler") {
      continue;
    }
    const existingId = byName.get(key);
    if (existingId !== undefined && existingId !== id) {
      throw new CharacterIdMapGenerateError("duplicate_character_name");
    }
    const existingName = idToName.get(id);
    if (existingName !== undefined && existingName !== key) {
      throw new CharacterIdMapGenerateError("duplicate_character_id");
    }
    byName.set(key, id);
    idToName.set(id, key);
  }

  if (byName.size === 0 && skippedInvalidIds > 0) {
    throw new CharacterIdMapGenerateError("invalid_character_id");
  }

  const amberId = byName.get("amber");
  if (!amberId) {
    throw new CharacterIdMapGenerateError("amber_missing");
  }
  // YShelper native alias; same public Amber id.
  byName.set("ambor", amberId);

  const sortedKeys = [...byName.keys()].sort((a, b) => a.localeCompare(b));
  const map: Record<string, string> = {};
  for (const key of sortedKeys) {
    map[key] = byName.get(key)!;
  }

  const count = Object.keys(map).length;
  if (count < minCount) {
    throw new CharacterIdMapGenerateError("map_too_small");
  }
  if (
    previous &&
    Object.keys(previous).length > 0 &&
    count < Math.ceil(Object.keys(previous).length * maxDropRatio)
  ) {
    throw new CharacterIdMapGenerateError("map_count_drop");
  }

  return { map, count };
}

export function renderCharacterIdMapSource(map: Record<string, string>): string {
  const lines = Object.keys(map)
    .sort((a, b) => a.localeCompare(b))
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])},`);
  return [
    "/**",
    " * English display-name → public Character.id (Amber / Genshin numeric).",
    " * Regenerated by: npm run yshelper:generate-character-map",
    " * Checked by: npm run yshelper:check-character-map",
    " * Traveler is intentionally omitted (fail-closed at native adapter).",
    " * Ambor is an explicit YShelper alias for Amber.",
    " */",
    "export const YSHELPER_CHARACTER_ID_BY_NAME: Readonly<Record<string, string>> = Object.freeze({",
    ...lines,
    "});",
    "",
  ].join("\n");
}

export function parseCharacterIdMapSource(source: string): CharacterIdMap {
  const start = source.indexOf("Object.freeze({");
  const end = source.lastIndexOf("});");
  if (start < 0 || end < 0 || end <= start) {
    throw new CharacterIdMapGenerateError("invalid_map_source");
  }
  const inner = source.slice(start + "Object.freeze({".length, end);
  const body = `{${inner}}`.replace(/,\s*}/g, "}");
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    throw new CharacterIdMapGenerateError("invalid_map_source");
  }
  if (!isRecord(parsed)) {
    throw new CharacterIdMapGenerateError("invalid_map_source");
  }
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (typeof value !== "string" || !CHARACTER_ID_PATTERN.test(value)) {
      throw new CharacterIdMapGenerateError("invalid_map_source");
    }
    out[key] = value;
  }
  return Object.freeze(out);
}

export function diffCharacterIdMaps(
  previous: CharacterIdMap,
  next: CharacterIdMap,
): {
  added: string[];
  removed: string[];
  changed: string[];
} {
  const added: string[] = [];
  const removed: string[] = [];
  const changed: string[] = [];
  for (const key of Object.keys(next)) {
    if (!(key in previous)) added.push(key);
    else if (previous[key] !== next[key]) changed.push(key);
  }
  for (const key of Object.keys(previous)) {
    if (!(key in next)) removed.push(key);
  }
  added.sort();
  removed.sort();
  changed.sort();
  return { added, removed, changed };
}

function extractAmberAvatarData(
  payload: unknown,
): Record<string, unknown> {
  if (!isRecord(payload)) {
    throw new CharacterIdMapGenerateError("invalid_amber_payload");
  }
  if (!("data" in payload)) {
    throw new CharacterIdMapGenerateError("missing_amber_data");
  }
  const data = payload.data;
  if (!isRecord(data)) {
    throw new CharacterIdMapGenerateError("invalid_amber_data");
  }
  // Project Amber list endpoints wrap avatars under data.items
  // (alongside props/types metadata keys).
  if (!isRecord(data.items) || Object.keys(data.items).length === 0) {
    throw new CharacterIdMapGenerateError("missing_amber_items");
  }
  return data.items;
}

function isTravelerId(id: string): boolean {
  return id === "10000005" || id === "10000007" || id.startsWith("10000005-");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
